SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60

PLAYER_SPEED = 5
PLAYER_BULLET_SIZE = 8
BULLET_SPEED = 7
ENEMY_BULLET_SPEED = 5
ENEMY_BULLET_SIZE = 8

INITIAL_ENEMY_SPEED = 2
INITIAL_ENEMY_SHOOT_PROB = 0.002